name: 'Hey From a GitHub Action'
on:
  push:
    branches: 
      - actions
description: 'Greet someone'
inputs:
  user:  
    description: 'Who to greet'
    required: true
    default: 'You'
runs:
  using: "composite"
  steps: 
    - run: echo Hey ${{ inputs.user }}.
      shell: bash